---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: echo
  namespace: spring-k8scm
automountServiceAccountToken: true
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: echo
  namespace: spring-k8scm
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods"]
    verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: echo-binding
  namespace: spring-k8scm
subjects:
  - kind: ServiceAccount
    name: echo
    namespace: spring-k8scm
roleRef:
  kind: Role
  name: echo
  apiGroup: rbac.authorization.k8s.io
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: echo-service-v1-config-yaml
  namespace: spring-k8scm
data:
  application.yaml: |-
    cm:
      tst: tval4
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: echo-service-v1-config-prop
  namespace: spring-k8scm
data:
  application.properties: |-
    cm.tst: tval2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  namespace: spring-k8scm
  labels:
    app: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      serviceAccountName: echo
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: app
          #image: <YOUR_IMAGE>
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
#          resources:
#            limits:
#              cpu: 100m
#              memory: 100Mi
#            requests:
#              cpu: 100m
#              memory: 100Mi
          env:
            - name: "KUBERNETES_NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
---
apiVersion: v1
kind: Service
metadata:
  name: echo
spec:
  selector:
    app: echo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echo-headless
spec:
  clusterIP: None
  selector:
    app: echo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080